### ISSUE TITLE
Package not working with Python3

### ISSUE THREAD

**Issue by artemistomaras** [gnosis/django-eth-events#1]
Line https://github.com/gnosis/django-eth-events/blob/master/django_eth_events/decoder.py#L28

gives the following error message under python3.5:
`[2017-09-21 10:21:10,712: ERROR/Worker-4] django_eth_events.tasks.event_listener[8db201af-c0e2-4755-828d-c7823cde840b]: 'bytes' object has no attribute 'encode'`

**Comment by denisgranha** [comment]
It was designed to be used with python 2.7, feel free to fork the repo and make changes :)

**Comment by artemistomaras** [comment]
I've forked the repo, made it python3 compatible and also added a few changes:
https://github.com/artemistomaras/django-eth-events/commits/master

**Comment by Uxio0** [comment]
Hi,

From version **1.0.36** and latter we are just supporting Python3, so I will close this issue.

Thank you for reporting :)
