### ISSUE TITLE
Package unavailable from pip

### ISSUE THREAD

**Issue by artemistomaras** [gnosis/django-eth-events#2]
The package cannot be installed via pip. It is currently available in TestPyPI and can be installed via running:
`pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple django-eth-events`

**Comment by denisgranha** [comment]
Hello @artemistoras , we know it, won't be availble on pip until we solve software license issues

**Comment by Uxio0** [comment]
Package can be downloaded from pip without issues now :)
