### ISSUE TITLE
No module named 'model_utils'

### ISSUE THREAD

**Issue by CodeMath** [gnosis/django-eth-events#20]
```
pip install django-eth-events
```
all requirements is installed and `$ python manage.py test.py`.

but got error 

```
No module named 'model_utils'
```

**Comment by Uxio0** [comment]
Thanks for the report and sorry for the late reply. It's fixed on b67a36c1dad7a7e5239945a2bbc16a7d2d4ba7b2 and already merged to master in #22, you can have it via pip from version v3.1.5 of django-eth-events onwards
